@startuml
participant Parent
participant Child

activate Parent
Parent -> Parent : on_setup()
activate Parent
deactivate Parent

Parent --> Child : fork() - failed
destroy Child

Parent -> Parent : on_fork_error()
activate Parent
deactivate Parent

Parent -> Parent : on_error()
activate Parent
deactivate Parent

@enduml